version: '3'
services:
  db:
    image: mongo:3.4
  server:
    image: node:8.1
    volumes:
      - ./server/:/server
    ports:
      - 3000:3000
    command: bash -c "cd /server && npm i"
  client:
    image: nginx:1.13
    volumes:
      - ./client/:/usr/share/nginx/html/
    ports:
      - 80:80