version: '3'
services:
  #team server mock api - rest
  teamapi:
    image: node:8.11.3
    container_name: teamapi
    volumes:
      - ./teamApi/:/teamApi
    ports:
      - 4040:4040
    command: bash -c "cd ./teamApi && npm i && node index.js"

    #players server mock api - rest
  playerapi:
    image: node:8.11.3
    container_name: playerapi
    volumes:
      - ./playersApi/:/playersApi
    ports:
      - 5050:5050
    command: bash -c "cd ./playersApi && npm i && node index.js"

  #apollo server - graphql#
  server:
    image: node:8.11.3
    volumes:
      - ./server/:/server
    ports:
      - 4000:4000
    command: bash -c "cd ./server && npm i && node index.js"

  #client dashboard#
  client:
    image: nginx:1.13
    volumes:
      - ./client/:/usr/share/nginx/html/
    ports:
      - 8080:80